monitor.bluez.rules = [
    {
        matches = [
            {
                "node.name" = "~bluez_output.*"
            }
        ]
        actions = {
            update-props = {
                "session.suspend-timeout-seconds" = 0
            }
        }
    }
]